# Generated by Django 5.1.7 on 2025-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordatorio',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='organismo',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='tiponotificacion',
            options={'verbose_name': 'Tipo de Notificación', 'verbose_name_plural': 'Tipos de Notificaciones'},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='enviada_email',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_envio_email',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='organismo',
        ),
        migrations.RemoveField(
            model_name='tiponotificacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tiponotificacion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tiponotificacion',
            name='para_admin_sma',
        ),
        migrations.RemoveField(
            model_name='tiponotificacion',
            name='para_ciudadanos',
        ),
        migrations.RemoveField(
            model_name='tiponotificacion',
            name='para_organismos',
        ),
        migrations.RemoveField(
            model_name='tiponotificacion',
            name='para_superadmin',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='enlace',
            field=models.CharField(blank=True, max_length=255, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='tiponotificacion',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tiponotificacion',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.DeleteModel(
            name='ConfiguracionNotificaciones',
        ),
        migrations.DeleteModel(
            name='Recordatorio',
        ),
    ]
