# Generated by Django 5.1.7 on 2025-04-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_tiponotificacion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponotificacion',
            name='para_admin_sma',
            field=models.BooleanField(default=False, verbose_name='Para Admin SMA'),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='para_ciudadanos',
            field=models.BooleanField(default=False, verbose_name='Para Ciudadanos'),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='para_organismos',
            field=models.BooleanField(default=False, verbose_name='Para Organismos'),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='para_superadmin',
            field=models.BooleanField(default=False, verbose_name='Para Superadmin'),
        ),
    ]
