# Generated by Django 5.1.7 on 2025-04-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0002_initial'),
        ('notificaciones', '0004_tiponotificacion_para_admin_sma_and_more'),
        ('organismos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='medidas.medida', verbose_name='Medida'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='organismos.organismo', verbose_name='Organismo'),
        ),
    ]
