# Generated by Django 5.1.7 on 2025-04-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medidas', '0001_initial'),
        ('organismos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('general', 'Reporte General'), ('organismo', 'Reporte por Organismo'), ('componente', 'Reporte por Componente')], max_length=20, verbose_name='Tipo')),
                ('acceso_superadmin', models.BooleanField(default=True, verbose_name='Acceso Superadmin')),
                ('acceso_admin_sma', models.BooleanField(default=True, verbose_name='Acceso Admin SMA')),
                ('acceso_organismos', models.BooleanField(default=False, verbose_name='Acceso Organismos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reportes',
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parámetros')),
                ('archivo', models.FileField(upload_to='reportes/%Y/%m/', verbose_name='Archivo')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='medidas.componente', verbose_name='Componente')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='organismos.organismo', verbose_name='Organismo')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
