# Generated by Django 5.1.7 on 2025-04-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoOrganismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Organismo',
                'verbose_name_plural': 'Tipos de Organismos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContactoOrganismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Contacto principal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='organismos.organismo', verbose_name='Organismo')),
            ],
            options={
                'verbose_name': 'Contacto de Organismo',
                'verbose_name_plural': 'Contactos de Organismos',
                'ordering': ['organismo', '-es_principal', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='organismo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organismos', to='organismos.tipoorganismo', verbose_name='Tipo de organismo'),
        ),
    ]
