# Generated by Django 5.1.7 on 2025-04-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organismos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('color', models.CharField(blank=True, help_text='Código hexadecimal del color, ej: #FF5733', max_length=7, verbose_name='Color')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Log de Medida',
                'verbose_name_plural': 'Logs de Medidas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de término')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('retrasada', 'Retrasada'), ('suspendida', 'Suspendida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de avance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de avance')),
                ('descripcion', models.TextField(verbose_name='Descripción del avance')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Archivo de evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Registro de Avance',
                'verbose_name_plural': 'Registros de Avance',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_coordinador', models.BooleanField(default=False, help_text='Indica si el organismo es el coordinador principal de esta medida', verbose_name='Es coordinador')),
                ('descripcion_responsabilidad', models.TextField(blank=True, verbose_name='Descripción de responsabilidad')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_medidas', to='organismos.organismo', verbose_name='Organismo')),
            ],
            options={
                'verbose_name': 'Asignación de Medida',
                'verbose_name_plural': 'Asignaciones de Medidas',
            },
        ),
    ]
