# Generated by Django 5.1.7 on 2025-04-18 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medidas', '0001_initial'),
        ('organismos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logmedida',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_medidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='medida',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='medidas.componente', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='medida',
            name='responsables',
            field=models.ManyToManyField(related_name='medidas_asignadas', through='medidas.AsignacionMedida', to='organismos.organismo', verbose_name='Organismos responsables'),
        ),
        migrations.AddField(
            model_name='logmedida',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medidas.medida', verbose_name='Medida'),
        ),
        migrations.AddField(
            model_name='asignacionmedida',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='medidas.medida', verbose_name='Medida'),
        ),
        migrations.AddField(
            model_name='registroavance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='registroavance',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_avance', to='medidas.medida', verbose_name='Medida'),
        ),
        migrations.AddField(
            model_name='registroavance',
            name='organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_avance', to='organismos.organismo', verbose_name='Organismo'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionmedida',
            unique_together={('medida', 'organismo')},
        ),
    ]
